const fullName = 'Anna Aksenov';
console.log('Full name:', fullName);
console.log(typeof fullName);
const isCool = true;
console.log('Is cool?:', isCool);
console.log(typeof isCool);
const totalPets = 2;
console.log('Total pets:', totalPets);
console.log(typeof totalPets);
const unknown = null;
console.log('Log unknown:', unknown);
console.log(typeof unknown);
let never;
console.log('Log never:', never);
console.log(typeof never);
